/* eslint-disable */
/**
 * Auto-generated by scripts/generate-solutions-scraped.mjs — do not edit by hand.
 */

export interface SolutionsScrapedEntry {
  slug: string;
  heroImage: string | null;
  galleryImages: string[];
  galleryAlts: string[];
  scrapedTitle: string;
  scrapedDescription: string;
  sectionTitles: string[];
  relatedLocalSlugs: string[];
}

export const solutionsScrapedBySlug: Record<string, SolutionsScrapedEntry> = {
  "commercial-office-acoustic": {
    "slug": "commercial-office-acoustic",
    "heroImage": "/solutions2/architectural-acoustics/commercial-office-acoustic/images/hero.webp",
    "galleryImages": [
      "/solutions2/architectural-acoustics/commercial-office-acoustic/images/content-001.webp",
      "/solutions2/architectural-acoustics/commercial-office-acoustic/images/content-002.webp",
      "/solutions2/architectural-acoustics/commercial-office-acoustic/images/content-003.webp",
      "/solutions2/architectural-acoustics/commercial-office-acoustic/images/content-004.webp",
      "/solutions2/architectural-acoustics/commercial-office-acoustic/images/content-005.webp",
      "/solutions2/architectural-acoustics/commercial-office-acoustic/images/content-006.webp",
      // "/solutions2/architectural-acoustics/commercial-office-acoustic/images/content-007.webp",
      "/solutions2/architectural-acoustics/commercial-office-acoustic/images/content-008.webp",
      "/solutions2/architectural-acoustics/commercial-office-acoustic/images/content-009.jpg",
      "/solutions2/architectural-acoustics/commercial-office-acoustic/images/content-010.jpg",
      "/solutions2/architectural-acoustics/commercial-office-acoustic/images/content-011.jpg",
      "/solutions2/architectural-acoustics/commercial-office-acoustic/images/content-012.jpg",
      "/solutions2/architectural-acoustics/commercial-office-acoustic/images/content-013.jpg",
      // "/solutions2/architectural-acoustics/commercial-office-acoustic/images/content-014.webp",
      // "/solutions2/architectural-acoustics/commercial-office-acoustic/images/content-015.webp",
      "/solutions2/architectural-acoustics/commercial-office-acoustic/images/content-016.jpg",
      "/solutions2/architectural-acoustics/commercial-office-acoustic/images/content-017.webp"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "G50S",
      "G65S",
      "Versailles",
      "Phantom",
      "Geometry",
      "ML",
      "L",
      "Matrix Acoustic Baffle",
      "Acoustic Art / Painting"
    ],
    "scrapedTitle": "Commercial Office",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "G50S",
      "G65S",
      "Versailles",
      "Phantom",
      "Geometry",
      "Matrix Acoustic Baffle",
      "Acoustic Art / Painting"
    ],
    "relatedLocalSlugs": [
      "acoustic-baffles",
      "imagine-acoustic-art"
    ]
  },
  "concert-halls-acoustic": {
    "slug": "concert-halls-acoustic",
    "heroImage": "/solutions2/architectural-acoustics/concert-halls-acoustic/images/hero.webp",
    "galleryImages": [
      "/solutions2/architectural-acoustics/concert-halls-acoustic/images/content-001.webp",
      "/solutions2/architectural-acoustics/concert-halls-acoustic/images/content-002.webp",
      "/solutions2/architectural-acoustics/concert-halls-acoustic/images/content-003.webp",
      "/solutions2/architectural-acoustics/concert-halls-acoustic/images/content-004.webp",
      "/solutions2/architectural-acoustics/concert-halls-acoustic/images/content-005.webp",
      // "/solutions2/architectural-acoustics/concert-halls-acoustic/images/content-006.webp",
      "/solutions2/architectural-acoustics/concert-halls-acoustic/images/content-007.jpg",
      "/solutions2/architectural-acoustics/concert-halls-acoustic/images/content-008.jpg",
      "/solutions2/architectural-acoustics/concert-halls-acoustic/images/content-009.jpg",
      "/solutions2/architectural-acoustics/concert-halls-acoustic/images/content-010.jpg",
      "/solutions2/architectural-acoustics/concert-halls-acoustic/images/content-011.jpg",
      "/solutions2/architectural-acoustics/concert-halls-acoustic/images/content-012.jpg",
      "/solutions2/architectural-acoustics/concert-halls-acoustic/images/content-013.jpg",
      // "/solutions2/architectural-acoustics/concert-halls-acoustic/images/content-014.webp"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "",
      "",
      "Hacker Acoustic Panel",
      "Combined Diffusion Unit",
      "Variable Sound Absorption and Diffusion Unit",
      "Mobile Acoustic Baffle",
      "Wave Acoustic Body",
      "Mobile Reflection Panel",
      "Musical Acoustic Shell",
      "Solid Wood Diffusion Unit",
      "Carbon Plastic Slotted Acoustic Panel"
    ],
    "scrapedTitle": "Concert halls acoustic",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "Hacker Acoustic Panel",
      "Combined Diffusion Unit",
      "Variable Sound Absorption and Diffusion Unit",
      "Mobile Acoustic Baffle",
      "Wave Acoustic Body",
      "Mobile Reflection Panel",
      "Musical Acoustic Shell",
      "Solid Wood Diffusion Unit",
      "Carbon Plastic Slotted Acoustic Panel"
    ],
    "relatedLocalSlugs": [
      "fabric-acoustic-panels",
      "acoustic-baffles"
    ]
  },
  "dining-areas-acoustic": {
    "slug": "dining-areas-acoustic",
    "heroImage": "/solutions2/architectural-acoustics/dining-areas-acoustic/images/hero.webp",
    "galleryImages": [
      "/solutions2/architectural-acoustics/dining-areas-acoustic/images/content-001.webp",
      "/solutions2/architectural-acoustics/dining-areas-acoustic/images/content-002.webp",
      "/solutions2/architectural-acoustics/dining-areas-acoustic/images/content-003.webp",
      "/solutions2/architectural-acoustics/dining-areas-acoustic/images/content-004.webp",
      "/solutions2/architectural-acoustics/dining-areas-acoustic/images/content-005.jpg",
      "/solutions2/architectural-acoustics/dining-areas-acoustic/images/content-006.jpg",
      "/solutions2/architectural-acoustics/dining-areas-acoustic/images/content-007.jpg",
      "/solutions2/architectural-acoustics/dining-areas-acoustic/images/content-008.jpg"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "",
      "Array Acoustic Baffle",
      "Matrix Acoustic Baffle",
      "Customized shape fabric acoustic panel",
      "Matrix Acoustic Baffle"
    ],
    "scrapedTitle": "Dining areas acoustic",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "Array Acoustic Baffle",
      "Matrix Acoustic Baffle",
      "Customized shape fabric acoustic panel"
    ],
    "relatedLocalSlugs": [
      "acoustic-baffles",
      "fabric-acoustic-panels"
    ]
  },
  "educational-spaces-acoustic": {
    "slug": "educational-spaces-acoustic",
    "heroImage": "/solutions2/architectural-acoustics/educational-spaces-acoustic/images/hero.webp",
    "galleryImages": [
      "/solutions2/architectural-acoustics/educational-spaces-acoustic/images/content-001.webp",
      "/solutions2/architectural-acoustics/educational-spaces-acoustic/images/content-002.webp",
      "/solutions2/architectural-acoustics/educational-spaces-acoustic/images/content-003.jpg",
      "/solutions2/architectural-acoustics/educational-spaces-acoustic/images/content-004.jpg",
      "/solutions2/architectural-acoustics/educational-spaces-acoustic/images/content-005.jpg",
      // "/solutions2/architectural-acoustics/educational-spaces-acoustic/images/content-006.webp",
      // "/solutions2/architectural-acoustics/educational-spaces-acoustic/images/content-007.webp",
      "/solutions2/architectural-acoustics/educational-spaces-acoustic/images/content-008.jpg",
      "/solutions2/architectural-acoustics/educational-spaces-acoustic/images/content-009.jpg",
      "/solutions2/architectural-acoustics/educational-spaces-acoustic/images/content-010.jpg",
      "/solutions2/architectural-acoustics/educational-spaces-acoustic/images/content-011.webp"
    ],
    "galleryAlts": [
      "",
      "",
      "Fabric acoustic panel",
      "Broadband Absorption Wall",
      "G50S",
      "SM",
      "ML",
      "Cloud Diffuser",
      "Customized shape fabric acoustic panel",
      "Matrix Acoustic Baffle",
      "Carbon Plastic Slotted Acoustic Panel"
    ],
    "scrapedTitle": "Educational Spaces",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "Fabric acoustic panel",
      "Broadband Absorption Wall",
      "G50S",
      "Cloud Diffuser",
      "Customized shape fabric acoustic panel",
      "Matrix Acoustic Baffle",
      "Carbon Plastic Slotted Acoustic Panel"
    ],
    "relatedLocalSlugs": [
      "fabric-acoustic-panels",
      "acoustic-baffles"
    ]
  },
  "entertainment-spaces-acoustic": {
    "slug": "entertainment-spaces-acoustic",
    "heroImage": "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/hero.webp",
    "galleryImages": [
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-001.webp",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-002.webp",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-003.webp",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-004.webp",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-005.webp",
      // "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-006.webp",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-007.jpg",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-008.jpg",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-009.jpg",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-010.webp",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-011.jpg",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-012.jpg",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-013.jpg",
      // "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-014.jpg",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-015.jpg",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-016.jpg",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-018.webp",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-019.jpg",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-020.webp",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-021.jpg",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-022.jpg",
      "/solutions2/architectural-acoustics/entertainment-spaces-acoustic/images/content-023.jpg"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "",
      "",
      "",
      "Array Acoustic Baffle",
      "Array Mesh Acoustic Baffle",
      "Array Acoustic Baffle",
      "Hacker Acoustic Panel",
      "Environmental Damping Sound Insulation Panel",
      "Metal Damping Sound Insulation Panel",
      "Composite Vibration Damping and Sound Insulation Panel",
      "Composite Damping Sound Insulation Panel",
      "Composite Damping Sound Insulation Panel",
      "Engineering Soundproof Door (Entertainment)",
      "Damping Sound Insulation Sheet (Double-Sided Self-Adhesive)",
      "SM",
      "Magic block acoustic panel",
      "Carbon Plastic Slotted Acoustic Panel",
      "Polymer Damping Brick",
      "Sound Insulation Damping Pad / Mat",
      "Floor Isolator / Vibration Damper"
    ],
    "scrapedTitle": "Entertainment spaces acoustic",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "Array Acoustic Baffle",
      "Array Mesh Acoustic Baffle",
      "Hacker Acoustic Panel",
      "Environmental Damping Sound Insulation Panel",
      "Metal Damping Sound Insulation Panel",
      "Composite Vibration Damping and Sound Insulation Panel",
      "Composite Damping Sound Insulation Panel",
      "Engineering Soundproof Door (Entertainment)",
      "Damping Sound Insulation Sheet (Double-Sided Self-Adhesive)",
      "Magic block acoustic panel",
      "Carbon Plastic Slotted Acoustic Panel",
      "Polymer Damping Brick",
      "Sound Insulation Damping Pad / Mat",
      "Floor Isolator / Vibration Damper"
    ],
    "relatedLocalSlugs": [
      "acoustic-baffles",
      "fabric-acoustic-panels",
      "sound-insulation",
      "soundproof-door"
    ]
  },
  "healthcare-facilities-acoustic": {
    "slug": "healthcare-facilities-acoustic",
    "heroImage": "/solutions2/architectural-acoustics/healthcare-facilities-acoustic/images/hero.webp",
    "galleryImages": [
      "/solutions2/architectural-acoustics/healthcare-facilities-acoustic/images/content-001.webp",
      "/solutions2/architectural-acoustics/healthcare-facilities-acoustic/images/content-002.webp",
      "/solutions2/architectural-acoustics/healthcare-facilities-acoustic/images/content-003.webp",
      "/solutions2/architectural-acoustics/healthcare-facilities-acoustic/images/content-004.webp",
      "/solutions2/architectural-acoustics/healthcare-facilities-acoustic/images/content-005.jpg",
      "/solutions2/architectural-acoustics/healthcare-facilities-acoustic/images/content-006.jpg",
      // "/solutions2/architectural-acoustics/healthcare-facilities-acoustic/images/content-007.webp"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "",
      "Engineering Soundproof Door (Hospital)",
      "Environmental Damping Sound Insulation Panel",
      "Carbon Plastic Slotted Acoustic Panel"
    ],
    "scrapedTitle": "Healthcare facilities acoustic",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "Engineering Soundproof Door (Hospital)",
      "Environmental Damping Sound Insulation Panel",
      "Carbon Plastic Slotted Acoustic Panel"
    ],
    "relatedLocalSlugs": [
      "soundproof-door",
      "sound-insulation",
      "fabric-acoustic-panels"
    ]
  },
  "hotels-and-hospitality-acoustic": {
    "slug": "hotels-and-hospitality-acoustic",
    "heroImage": "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/hero.webp",
    "galleryImages": [
      "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/content-001.webp",
      "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/content-002.webp",
      "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/content-003.webp",
      "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/content-004.webp",
      "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/content-005.webp",
      // "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/content-006.webp",
      // "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/content-007.webp",
      "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/content-008.webp",
      "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/content-009.webp",
      // "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/content-010.webp",
      "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/content-011.jpg",
      "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/content-012.webp",
      "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/content-013.jpg",
      // "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/content-014.jpg",
      "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/content-015.jpg",
      "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/content-016.jpg",
      "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/content-017.webp",
      "/solutions2/architectural-acoustics/hotels-and-hospitality-acoustic/images/content-018.png"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Engineering Soundproof Door",
      "Byer Acoustic Cotton",
      "Damping Sound Insulation Sheet (Single-Sided Aluminum Foil)",
      "Home Silent Pod",
      "Floor Damping Sound-Insulating Coating",
      "Damping Sound-Insulating Flooring (Wood Grain)",
      "Acoustic Art / Painting",
      "Low-Noise Exhaust Fan"
    ],
    "scrapedTitle": "Hotels and Hospitality",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "Engineering Soundproof Door",
      "Byer Acoustic Cotton",
      "Damping Sound Insulation Sheet (Single-Sided Aluminum Foil)",
      "Home Silent Pod",
      "Floor Damping Sound-Insulating Coating",
      "Damping Sound-Insulating Flooring (Wood Grain)",
      "Acoustic Art / Painting",
      "Low-Noise Exhaust Fan"
    ],
    "relatedLocalSlugs": [
      "soundproof-door",
      "sound-insulation",
      "imagine-acoustic-art",
      "silent-exhaust-fans"
    ]
  },
  "multi-functional-halls-acoustic": {
    "slug": "multi-functional-halls-acoustic",
    "heroImage": "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/hero.webp",
    "galleryImages": [
      "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/content-001.webp",
      "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/content-002.webp",
      "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/content-003.webp",
      "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/content-004.webp",
      "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/content-005.webp",
      // "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/content-006.webp",
      "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/content-007.jpg",
      "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/content-008.jpg",
      "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/content-009.jpg",
      "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/content-010.webp",
      "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/content-011.webp",
      "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/content-012.webp",
      "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/content-013.webp",
      // "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/content-014.webp",
      "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/content-015.jpg",
      "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/content-016.jpg",
      "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/content-018.jpg",
      "/solutions2/architectural-acoustics/multi-functional-halls-acoustic/images/content-019.webp"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "",
      "",
      "",
      "Array Acoustic Baffle",
      "Matrix Acoustic Baffle",
      "Fabric acoustic panel",
      "Hacker Acoustic Panel",
      "Matrix Acoustic Panel",
      "Honeycomb Acoustic Panel",
      "Broadband Acoustic Panel",
      "Slotted Acoustic Panel",
      "Variable Sound Absorption and Diffusion Unit",
      "Variable Sound Absorption and Diffusion Unit",
      "Matrix Acoustic Baffle",
      "Carbon Plastic Slotted Acoustic Panel"
    ],
    "scrapedTitle": "Multi-functional halls acoustic",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "Array Acoustic Baffle",
      "Matrix Acoustic Baffle",
      "Fabric acoustic panel",
      "Hacker Acoustic Panel",
      "Matrix Acoustic Panel",
      "Honeycomb Acoustic Panel",
      "Broadband Acoustic Panel",
      "Slotted Acoustic Panel",
      "Variable Sound Absorption and Diffusion Unit",
      "Solid Wood Diffusion Unit",
      "Carbon Plastic Slotted Acoustic Panel"
    ],
    "relatedLocalSlugs": [
      "acoustic-baffles",
      "fabric-acoustic-panels"
    ]
  },
  "residential-homes-acoustic": {
    "slug": "residential-homes-acoustic",
    "heroImage": "/solutions2/architectural-acoustics/residential-homes-acoustic/images/hero.webp",
    "galleryImages": [
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-001.jpg",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-002.jpg",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-003.jpg",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-004.webp",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-005.jpg",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-006.jpg",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-007.jpg",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-008.jpg",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-009.jpg",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-010.jpg",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-011.webp",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-012.jpg",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-013.webp",
      // "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-014.jpg",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-015.jpg",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-016.webp",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-018.jpg",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-019.jpg",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-020.jpg",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-021.jpg",
      "/solutions2/architectural-acoustics/residential-homes-acoustic/images/content-022.webp"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "G50M",
      "G50MP",
      "Damping Sound Insulation Sheet (Single-Sided Aluminum Foil)",
      "Wafer Holographic Acoustic Module",
      "Home Silent Pod",
      "Ultra-Thin Isolator / Vibration Damper",
      "Ceiling Isolator / Vibration Damper",
      "Sound Insulation Damping Pad / Mat",
      "Sound Insulation Damping Sealant / Sealant Applicator Gun",
      "Acoustic Art / Painting"
    ],
    "scrapedTitle": "Residential Homes",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "G50M",
      "G50MP",
      "Damping Sound Insulation Sheet (Single-Sided Aluminum Foil)",
      "Wafer Holographic Acoustic Module",
      "Home Silent Pod",
      "Ultra-Thin Isolator / Vibration Damper",
      "Ceiling Isolator / Vibration Damper",
      "Sound Insulation Damping Pad / Mat",
      "Sound Insulation Damping Sealant / Sealant Applicator Gun",
      "Acoustic Art / Painting"
    ],
    "relatedLocalSlugs": [
      "sound-insulation",
      "holographic-acoustic-module",
      "imagine-acoustic-art"
    ]
  },
  "venue-spaces-acoustic": {
    "slug": "venue-spaces-acoustic",
    "heroImage": "/solutions2/architectural-acoustics/venue-spaces-acoustic/images/hero.webp",
    "galleryImages": [
      "/solutions2/architectural-acoustics/venue-spaces-acoustic/images/content-001.webp",
      "/solutions2/architectural-acoustics/venue-spaces-acoustic/images/content-002.webp",
      "/solutions2/architectural-acoustics/venue-spaces-acoustic/images/content-003.jpg",
      "/solutions2/architectural-acoustics/venue-spaces-acoustic/images/content-004.jpg",
      "/solutions2/architectural-acoustics/venue-spaces-acoustic/images/content-005.jpg",
      "/solutions2/architectural-acoustics/venue-spaces-acoustic/images/content-006.jpg",
      // "/solutions2/architectural-acoustics/venue-spaces-acoustic/images/content-007.webp",
      "/solutions2/architectural-acoustics/venue-spaces-acoustic/images/content-008.webp",
      "/solutions2/architectural-acoustics/venue-spaces-acoustic/images/content-009.webp",
      "/solutions2/architectural-acoustics/venue-spaces-acoustic/images/content-010.jpg",
      "/solutions2/architectural-acoustics/venue-spaces-acoustic/images/content-011.jpg",
      "/solutions2/architectural-acoustics/venue-spaces-acoustic/images/content-012.webp"
    ],
    "galleryAlts": [
      "",
      "",
      "Array Acoustic Baffle",
      "Array Mesh Acoustic Baffle",
      "Array Acoustic Baffle",
      "Matrix Acoustic Baffle",
      "Hacker Acoustic Panel",
      "Honeycomb Acoustic Panel",
      "Broadband Acoustic Panel",
      "Energy Acoustic Reflection Panel",
      "Matrix Acoustic Baffle",
      "Carbon Plastic Slotted Acoustic Panel"
    ],
    "scrapedTitle": "Venue spaces acoustic",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "Array Acoustic Baffle",
      "Array Mesh Acoustic Baffle",
      "Matrix Acoustic Baffle",
      "Hacker Acoustic Panel",
      "Honeycomb Acoustic Panel",
      "Broadband Acoustic Panel",
      "Energy Acoustic Reflection Panel",
      "Carbon Plastic Slotted Acoustic Panel"
    ],
    "relatedLocalSlugs": [
      "acoustic-baffles",
      "fabric-acoustic-panels"
    ]
  },
  "cooling-towers-noise-control": {
    "slug": "cooling-towers-noise-control",
    "heroImage": "/solutions2/environmental-noise-control/cooling-towers-noise-control/images/hero.webp",
    "galleryImages": [
      "/solutions2/environmental-noise-control/cooling-towers-noise-control/images/content-001.jpg",
      "/solutions2/environmental-noise-control/cooling-towers-noise-control/images/content-002.jpg",
      "/solutions2/environmental-noise-control/cooling-towers-noise-control/images/content-003.jpg",
      "/solutions2/environmental-noise-control/cooling-towers-noise-control/images/content-004.jpg",
      "/solutions2/environmental-noise-control/cooling-towers-noise-control/images/content-005.jpg",
      "/solutions2/environmental-noise-control/cooling-towers-noise-control/images/content-006.jpg",
      "/solutions2/environmental-noise-control/cooling-towers-noise-control/images/content-007.jpg",
      "/solutions2/environmental-noise-control/cooling-towers-noise-control/images/content-008.png",
      "/solutions2/environmental-noise-control/cooling-towers-noise-control/images/content-009.webp",
      "/solutions2/environmental-noise-control/cooling-towers-noise-control/images/content-010.jpg",
      "/solutions2/environmental-noise-control/cooling-towers-noise-control/images/content-011.jpg",
      "/solutions2/environmental-noise-control/cooling-towers-noise-control/images/content-012.jpg"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Floor Isolator / Vibration Damper"
    ],
    "scrapedTitle": "Cooling towers noise control",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Floor Isolator / Vibration Damper"
    ],
    "relatedLocalSlugs": []
  },
  "factories-and-industrial-plants-acoustic": {
    "slug": "factories-and-industrial-plants-acoustic",
    "heroImage": "/solutions2/environmental-noise-control/factories-and-industrial-plants-acoustic/images/hero.webp",
    "galleryImages": [
      "/solutions2/environmental-noise-control/factories-and-industrial-plants-acoustic/images/content-001.jpg",
      "/solutions2/environmental-noise-control/factories-and-industrial-plants-acoustic/images/content-002.jpg",
      "/solutions2/environmental-noise-control/factories-and-industrial-plants-acoustic/images/content-003.jpg",
      "/solutions2/environmental-noise-control/factories-and-industrial-plants-acoustic/images/content-004.jpg",
      "/solutions2/environmental-noise-control/factories-and-industrial-plants-acoustic/images/content-005.jpg",
      "/solutions2/environmental-noise-control/factories-and-industrial-plants-acoustic/images/content-006.jpg",
      "/solutions2/environmental-noise-control/factories-and-industrial-plants-acoustic/images/content-007.jpg",
      "/solutions2/environmental-noise-control/factories-and-industrial-plants-acoustic/images/content-008.png",
      "/solutions2/environmental-noise-control/factories-and-industrial-plants-acoustic/images/content-009.webp",
      "/solutions2/environmental-noise-control/factories-and-industrial-plants-acoustic/images/content-010.jpg",
      "/solutions2/environmental-noise-control/factories-and-industrial-plants-acoustic/images/content-011.jpg",
      "/solutions2/environmental-noise-control/factories-and-industrial-plants-acoustic/images/content-012.jpg"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Floor Isolator / Vibration Damper"
    ],
    "scrapedTitle": "Factories and Industrial Plants acoustic",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Floor Isolator / Vibration Damper"
    ],
    "relatedLocalSlugs": []
  },
  "highways-noise-control": {
    "slug": "highways-noise-control",
    "heroImage": "/solutions2/environmental-noise-control/highways-noise-control/images/hero.webp",
    "galleryImages": [
      "/solutions2/environmental-noise-control/highways-noise-control/images/content-001.jpg",
      "/solutions2/environmental-noise-control/highways-noise-control/images/content-002.jpg",
      "/solutions2/environmental-noise-control/highways-noise-control/images/content-003.jpg",
      "/solutions2/environmental-noise-control/highways-noise-control/images/content-004.jpg",
      "/solutions2/environmental-noise-control/highways-noise-control/images/content-005.jpg",
      "/solutions2/environmental-noise-control/highways-noise-control/images/content-006.jpg",
      "/solutions2/environmental-noise-control/highways-noise-control/images/content-007.png",
      "/solutions2/environmental-noise-control/highways-noise-control/images/content-008.webp",
      "/solutions2/environmental-noise-control/highways-noise-control/images/content-009.jpg",
      "/solutions2/environmental-noise-control/highways-noise-control/images/content-010.jpg",
      "/solutions2/environmental-noise-control/highways-noise-control/images/content-011.jpg"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "",
      "",
      "",
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Floor Isolator / Vibration Damper"
    ],
    "scrapedTitle": "Highways noise control",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Floor Isolator / Vibration Damper"
    ],
    "relatedLocalSlugs": []
  },
  "hydroelectric-power-stations-acoustic": {
    "slug": "hydroelectric-power-stations-acoustic",
    "heroImage": "/solutions2/environmental-noise-control/hydroelectric-power-stations-acoustic/images/hero.webp",
    "galleryImages": [
      "/solutions2/environmental-noise-control/hydroelectric-power-stations-acoustic/images/content-001.jpg",
      "/solutions2/environmental-noise-control/hydroelectric-power-stations-acoustic/images/content-002.jpg",
      "/solutions2/environmental-noise-control/hydroelectric-power-stations-acoustic/images/content-003.jpg",
      "/solutions2/environmental-noise-control/hydroelectric-power-stations-acoustic/images/content-004.jpg",
      "/solutions2/environmental-noise-control/hydroelectric-power-stations-acoustic/images/content-005.jpg",
      "/solutions2/environmental-noise-control/hydroelectric-power-stations-acoustic/images/content-006.jpg",
      "/solutions2/environmental-noise-control/hydroelectric-power-stations-acoustic/images/content-007.jpg",
      "/solutions2/environmental-noise-control/hydroelectric-power-stations-acoustic/images/content-008.jpg",
      "/solutions2/environmental-noise-control/hydroelectric-power-stations-acoustic/images/content-009.jpg",
      "/solutions2/environmental-noise-control/hydroelectric-power-stations-acoustic/images/content-010.jpg",
      "/solutions2/environmental-noise-control/hydroelectric-power-stations-acoustic/images/content-011.jpg",
      "/solutions2/environmental-noise-control/hydroelectric-power-stations-acoustic/images/content-012.png",
      "/solutions2/environmental-noise-control/hydroelectric-power-stations-acoustic/images/content-013.webp",
      "/solutions2/environmental-noise-control/hydroelectric-power-stations-acoustic/images/content-014.jpg",
      "/solutions2/environmental-noise-control/hydroelectric-power-stations-acoustic/images/content-015.jpg",
      "/solutions2/environmental-noise-control/hydroelectric-power-stations-acoustic/images/content-016.jpg"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Floor Isolator / Vibration Damper"
    ],
    "scrapedTitle": "Hydroelectric power stations acoustic",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Floor Isolator / Vibration Damper"
    ],
    "relatedLocalSlugs": []
  },
  "piping-and-duct-systems-acoustic": {
    "slug": "piping-and-duct-systems-acoustic",
    "heroImage": "/solutions2/environmental-noise-control/piping-and-duct-systems-acoustic/images/hero.webp",
    "galleryImages": [
      "/solutions2/environmental-noise-control/piping-and-duct-systems-acoustic/images/content-001.jpg",
      "/solutions2/environmental-noise-control/piping-and-duct-systems-acoustic/images/content-002.jpg",
      "/solutions2/environmental-noise-control/piping-and-duct-systems-acoustic/images/content-003.jpg",
      "/solutions2/environmental-noise-control/piping-and-duct-systems-acoustic/images/content-004.jpg",
      "/solutions2/environmental-noise-control/piping-and-duct-systems-acoustic/images/content-005.jpg",
      "/solutions2/environmental-noise-control/piping-and-duct-systems-acoustic/images/content-006.jpg",
      "/solutions2/environmental-noise-control/piping-and-duct-systems-acoustic/images/content-007.jpg",
      "/solutions2/environmental-noise-control/piping-and-duct-systems-acoustic/images/content-008.png",
      "/solutions2/environmental-noise-control/piping-and-duct-systems-acoustic/images/content-009.webp",
      "/solutions2/environmental-noise-control/piping-and-duct-systems-acoustic/images/content-010.jpg",
      "/solutions2/environmental-noise-control/piping-and-duct-systems-acoustic/images/content-011.jpg",
      "/solutions2/environmental-noise-control/piping-and-duct-systems-acoustic/images/content-012.jpg"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Floor Isolator / Vibration Damper"
    ],
    "scrapedTitle": "Piping and duct systems acoustic",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Floor Isolator / Vibration Damper"
    ],
    "relatedLocalSlugs": []
  },
  "subways-noise-control": {
    "slug": "subways-noise-control",
    "heroImage": "/solutions2/environmental-noise-control/subways-noise-control/images/hero.webp",
    "galleryImages": [
      "/solutions2/environmental-noise-control/subways-noise-control/images/content-001.jpg",
      "/solutions2/environmental-noise-control/subways-noise-control/images/content-002.jpg",
      "/solutions2/environmental-noise-control/subways-noise-control/images/content-003.jpg",
      "/solutions2/environmental-noise-control/subways-noise-control/images/content-004.jpg",
      "/solutions2/environmental-noise-control/subways-noise-control/images/content-005.jpg",
      "/solutions2/environmental-noise-control/subways-noise-control/images/content-006.jpg",
      "/solutions2/environmental-noise-control/subways-noise-control/images/content-007.jpg",
      "/solutions2/environmental-noise-control/subways-noise-control/images/content-008.jpg",
      "/solutions2/environmental-noise-control/subways-noise-control/images/content-009.png",
      "/solutions2/environmental-noise-control/subways-noise-control/images/content-010.webp",
      "/solutions2/environmental-noise-control/subways-noise-control/images/content-011.jpg",
      "/solutions2/environmental-noise-control/subways-noise-control/images/content-012.jpg",
      "/solutions2/environmental-noise-control/subways-noise-control/images/content-013.jpg"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Floor Isolator / Vibration Damper"
    ],
    "scrapedTitle": "Subways noise control",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Floor Isolator / Vibration Damper"
    ],
    "relatedLocalSlugs": []
  },
  "tunnels-noise-control": {
    "slug": "tunnels-noise-control",
    "heroImage": "/solutions2/environmental-noise-control/tunnels-noise-control/images/hero.webp",
    "galleryImages": [
      "/solutions2/environmental-noise-control/tunnels-noise-control/images/content-001.jpg",
      "/solutions2/environmental-noise-control/tunnels-noise-control/images/content-002.jpg",
      "/solutions2/environmental-noise-control/tunnels-noise-control/images/content-003.jpg",
      "/solutions2/environmental-noise-control/tunnels-noise-control/images/content-004.jpg",
      "/solutions2/environmental-noise-control/tunnels-noise-control/images/content-005.jpg",
      "/solutions2/environmental-noise-control/tunnels-noise-control/images/content-006.jpg",
      "/solutions2/environmental-noise-control/tunnels-noise-control/images/content-007.png",
      "/solutions2/environmental-noise-control/tunnels-noise-control/images/content-008.webp",
      "/solutions2/environmental-noise-control/tunnels-noise-control/images/content-009.jpg",
      "/solutions2/environmental-noise-control/tunnels-noise-control/images/content-010.jpg",
      "/solutions2/environmental-noise-control/tunnels-noise-control/images/content-011.jpg"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "",
      "",
      "",
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Floor Isolator / Vibration Damper"
    ],
    "scrapedTitle": "Tunnels noise control",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Floor Isolator / Vibration Damper"
    ],
    "relatedLocalSlugs": []
  },
  "armored-vehicles-noise-reduction": {
    "slug": "armored-vehicles-noise-reduction",
    "heroImage": "/solutions2/industrial-facilities/armored-vehicles-noise-reduction/images/hero.webp",
    "galleryImages": [
      "/solutions2/industrial-facilities/armored-vehicles-noise-reduction/images/content-001.jpg",
      "/solutions2/industrial-facilities/armored-vehicles-noise-reduction/images/content-002.jpg",
      "/solutions2/industrial-facilities/armored-vehicles-noise-reduction/images/content-003.jpg",
      "/solutions2/industrial-facilities/armored-vehicles-noise-reduction/images/content-004.png",
      "/solutions2/industrial-facilities/armored-vehicles-noise-reduction/images/content-005.webp",
      "/solutions2/industrial-facilities/armored-vehicles-noise-reduction/images/content-006.jpg",
      "/solutions2/industrial-facilities/armored-vehicles-noise-reduction/images/content-007.jpg",
      "/solutions2/industrial-facilities/armored-vehicles-noise-reduction/images/content-008.jpg",
      "/solutions2/industrial-facilities/armored-vehicles-noise-reduction/images/content-009.jpg",
      "/solutions2/industrial-facilities/armored-vehicles-noise-reduction/images/content-010.jpg",
      "/solutions2/industrial-facilities/armored-vehicles-noise-reduction/images/content-011.jpg"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Sound Insulation Sheet (Single-Sided Aluminum Foil)",
      "Polymer Sound Insulation Felt",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Sound Insulation Damping Pad / Mat",
      "Floor Isolator / Vibration Damper"
    ],
    "scrapedTitle": "Armored vehicles noise reduction",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Sound Insulation Sheet (Single-Sided Aluminum Foil)",
      "Polymer Sound Insulation Felt",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Sound Insulation Damping Pad / Mat",
      "Floor Isolator / Vibration Damper"
    ],
    "relatedLocalSlugs": [
      "sound-insulation"
    ]
  },
  "high-speed-rail-noise-reduction": {
    "slug": "high-speed-rail-noise-reduction",
    "heroImage": "/solutions2/industrial-facilities/high-speed-rail-noise-reduction/images/hero.jpg",
    "galleryImages": [
      "/solutions2/industrial-facilities/high-speed-rail-noise-reduction/images/content-001.jpg",
      "/solutions2/industrial-facilities/high-speed-rail-noise-reduction/images/content-002.jpg",
      "/solutions2/industrial-facilities/high-speed-rail-noise-reduction/images/content-003.jpg",
      "/solutions2/industrial-facilities/high-speed-rail-noise-reduction/images/content-004.jpg",
      "/solutions2/industrial-facilities/high-speed-rail-noise-reduction/images/content-005.png",
      "/solutions2/industrial-facilities/high-speed-rail-noise-reduction/images/content-006.webp",
      "/solutions2/industrial-facilities/high-speed-rail-noise-reduction/images/content-007.jpg",
      "/solutions2/industrial-facilities/high-speed-rail-noise-reduction/images/content-008.jpg",
      "/solutions2/industrial-facilities/high-speed-rail-noise-reduction/images/content-009.jpg",
      "/solutions2/industrial-facilities/high-speed-rail-noise-reduction/images/content-010.jpg",
      "/solutions2/industrial-facilities/high-speed-rail-noise-reduction/images/content-011.jpg",
      "/solutions2/industrial-facilities/high-speed-rail-noise-reduction/images/content-012.jpg"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "",
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Sound Insulation Sheet (Single-Sided Aluminum Foil)",
      "Polymer Sound Insulation Felt",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Sound Insulation Damping Pad / Mat",
      "Floor Isolator / Vibration Damper"
    ],
    "scrapedTitle": "High speed rail noise reduction",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Sound Insulation Sheet (Single-Sided Aluminum Foil)",
      "Polymer Sound Insulation Felt",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Sound Insulation Damping Pad / Mat",
      "Floor Isolator / Vibration Damper"
    ],
    "relatedLocalSlugs": [
      "sound-insulation"
    ]
  },
  "marine-vessels-noise-reduction": {
    "slug": "marine-vessels-noise-reduction",
    "heroImage": "/solutions2/industrial-facilities/marine-vessels-noise-reduction/images/hero.jpg",
    "galleryImages": [
      "/solutions2/industrial-facilities/marine-vessels-noise-reduction/images/content-001.jpg",
      "/solutions2/industrial-facilities/marine-vessels-noise-reduction/images/content-002.jpg",
      "/solutions2/industrial-facilities/marine-vessels-noise-reduction/images/content-003.jpg",
      "/solutions2/industrial-facilities/marine-vessels-noise-reduction/images/content-004.jpg",
      "/solutions2/industrial-facilities/marine-vessels-noise-reduction/images/content-005.png",
      "/solutions2/industrial-facilities/marine-vessels-noise-reduction/images/content-006.webp",
      "/solutions2/industrial-facilities/marine-vessels-noise-reduction/images/content-007.jpg",
      "/solutions2/industrial-facilities/marine-vessels-noise-reduction/images/content-008.jpg",
      "/solutions2/industrial-facilities/marine-vessels-noise-reduction/images/content-009.jpg",
      "/solutions2/industrial-facilities/marine-vessels-noise-reduction/images/content-010.jpg",
      "/solutions2/industrial-facilities/marine-vessels-noise-reduction/images/content-011.jpg",
      "/solutions2/industrial-facilities/marine-vessels-noise-reduction/images/content-012.jpg"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "",
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Sound Insulation Sheet (Single-Sided Aluminum Foil)",
      "Polymer Sound Insulation Felt",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Sound Insulation Damping Pad / Mat",
      "Floor Isolator / Vibration Damper"
    ],
    "scrapedTitle": "Marine Vessels",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Sound Insulation Sheet (Single-Sided Aluminum Foil)",
      "Polymer Sound Insulation Felt",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Sound Insulation Damping Pad / Mat",
      "Floor Isolator / Vibration Damper"
    ],
    "relatedLocalSlugs": [
      "sound-insulation"
    ]
  },
  "product-car": {
    "slug": "product-car",
    "heroImage": "/solutions2/industrial-facilities/product-car/images/hero.jpg",
    "galleryImages": [
      "/solutions2/industrial-facilities/product-car/images/content-001.webp",
      "/solutions2/industrial-facilities/product-car/images/content-002.webp",
      "/solutions2/industrial-facilities/product-car/images/content-003.jpg",
      "/solutions2/industrial-facilities/product-car/images/content-004.jpg",
      "/solutions2/industrial-facilities/product-car/images/content-005.jpg",
      "/solutions2/industrial-facilities/product-car/images/content-006.jpg",
      "/solutions2/industrial-facilities/product-car/images/content-007.jpg",
      "/solutions2/industrial-facilities/product-car/images/content-008.jpg",
      "/solutions2/industrial-facilities/product-car/images/content-009.jpg",
      "/solutions2/industrial-facilities/product-car/images/content-010.jpg",
      "/solutions2/industrial-facilities/product-car/images/content-011.jpg",
      "/solutions2/industrial-facilities/product-car/images/content-012.webp"
    ],
    "galleryAlts": [
      "Car NVH",
      "Car NVH",
      "Car NVH",
      "Car NVH",
      "Car NVH",
      "Chassis Kit",
      "Trunk Kit",
      "Four Wheels Kit",
      "Four Doors Kit",
      "Hood Kit",
      "Sealing Kit",
      "Car NVH"
    ],
    "scrapedTitle": "SoundBox - Car NVH",
    "scrapedDescription": "NVH is an important indicator for measuring automotive quality and a focus of international automobile manufacturers. It is a complex and difficult-to-solve comprehensive technical problem. Soundbox has 15 years of acoustic practice and has accumulated an experienced team in analyzing and solving various noise and vibration issues. Based on powerful acoustic simulation technology, we manufacture high-performance complete materials most conducive to solving NVH. These materials consist of energy-absorbing materials with significant IIR damping factors, Bayer acoustic cotton manufactured using electrostatic ultrafine spinning technology, and air-sealing materials. Such equipment is undoubtedly prepared to absorb body sheet metal vibration noise and consume cavity layer noise in the body structure. Similarly, it has strict requirements for ecology, environmental protection, and safety, which is Soundbox's value mission.",
    "sectionTitles": [],
    "relatedLocalSlugs": []
  },
  "warships-noise-reduction": {
    "slug": "warships-noise-reduction",
    "heroImage": "/solutions2/industrial-facilities/warships-noise-reduction/images/hero.jpg",
    "galleryImages": [
      "/solutions2/industrial-facilities/warships-noise-reduction/images/content-001.jpg",
      "/solutions2/industrial-facilities/warships-noise-reduction/images/content-002.jpg",
      "/solutions2/industrial-facilities/warships-noise-reduction/images/content-003.jpg",
      "/solutions2/industrial-facilities/warships-noise-reduction/images/content-004.png",
      "/solutions2/industrial-facilities/warships-noise-reduction/images/content-005.webp",
      "/solutions2/industrial-facilities/warships-noise-reduction/images/content-006.jpg",
      "/solutions2/industrial-facilities/warships-noise-reduction/images/content-007.jpg",
      "/solutions2/industrial-facilities/warships-noise-reduction/images/content-008.jpg",
      "/solutions2/industrial-facilities/warships-noise-reduction/images/content-009.jpg",
      "/solutions2/industrial-facilities/warships-noise-reduction/images/content-010.jpg",
      "/solutions2/industrial-facilities/warships-noise-reduction/images/content-011.jpg"
    ],
    "galleryAlts": [
      "",
      "",
      "",
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Sound Insulation Sheet (Single-Sided Aluminum Foil)",
      "Polymer Sound Insulation Felt",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Sound Insulation Damping Pad / Mat",
      "Floor Isolator / Vibration Damper"
    ],
    "scrapedTitle": "Warships noise reduction",
    "scrapedDescription": "SoundBox solution details page",
    "sectionTitles": [
      "White Fiber Environmental Acoustic Cotton",
      "Byer Acoustic Cotton",
      "Damping Sound Insulation Sheet (Single-Sided Aluminum Foil)",
      "Polymer Sound Insulation Felt",
      "Damping Vibration Reduction Paint (Water-based)",
      "Polymer Damping Brick",
      "Sound Insulation Damping Pad / Mat",
      "Floor Isolator / Vibration Damper"
    ],
    "relatedLocalSlugs": [
      "sound-insulation"
    ]
  }
};
